# -*- coding: utf-8 -*-
"""Bank Churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WiMrtC4oAPdR3fZOQxSxlX3YGoagYsIl

# 📊 **Entrega #01: Análise Exploratória de Dados (EDA)**  
### 🚀 Conjunto de Dados: Bank Churn (Rotatividade Bancária)  
**Metodologia:** CRISP-DM — Fase: Entendimento dos Dados

---

## 👥 **DataStorm**
- Filipe Cayres Kelmer (cayresfilipe@gmail.com)
- Maria Naiara Lima Flor (maria.naiara.lima@gmail.com)
- Clara Alyne de Aguiar (claraalyneaguiar04@gmail.com)
- Neiviene Costa (neive0009@gmail.com)
- Alana Silva Sales (alanasilvasales37@gmail.com)
"""

# Importar bibliotecas
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Configurar visualizações
sns.set(style="whitegrid")
pd.set_option('display.max_columns', None)

# Carregar dataset
url = 'https://raw.githubusercontent.com/atlantico-academy/datasets/refs/heads/main/churn.csv'
df = pd.read_csv(url)

# Visualizar as primeiras linhas
df.head()

# 📑 Dicionário de Dados - Análise Exploratória

import pandas as pd

df_dict = pd.DataFrame([
    {
        "Variável": "RowNumber",
        "Descrição": "Índice da linha no dataset (número sequencial).",
        "Tipo": "Quantitativa",
        "Subtipo": "Discreta",
        "Relevância": "Não útil"
    },
    {
        "Variável": "CustomerId",
        "Descrição": "Identificador único de cada cliente.",
        "Tipo": "Qualitativa",
        "Subtipo": "Nominal",
        "Relevância": "Não útil"
    },
    {
        "Variável": "Surname",
        "Descrição": "Sobrenome do cliente.",
        "Tipo": "Qualitativa",
        "Subtipo": "Nominal",
        "Relevância": "Não útil"
    },
    {
        "Variável": "CreditScore",
        "Descrição": "Pontuação de crédito do cliente.",
        "Tipo": "Quantitativa",
        "Subtipo": "Contínua",
        "Relevância": "Útil"
    },
    {
        "Variável": "Geography",
        "Descrição": "País de residência do cliente.",
        "Tipo": "Qualitativa",
        "Subtipo": "Nominal",
        "Relevância": "Útil"
    },
    {
        "Variável": "Gender",
        "Descrição": "Sexo do cliente.",
        "Tipo": "Qualitativa",
        "Subtipo": "Nominal",
        "Relevância": "Útil"
    },
    {
        "Variável": "Age",
        "Descrição": "Idade do cliente (em anos).",
        "Tipo": "Quantitativa",
        "Subtipo": "Contínua",
        "Relevância": "Útil"
    },
    {
        "Variável": "Tenure",
        "Descrição": "Tempo (em anos) que o cliente é fiel ao banco.",
        "Tipo": "Quantitativa",
        "Subtipo": "Discreta",
        "Relevância": "Útil"
    },
    {
        "Variável": "Balance",
        "Descrição": "Saldo disponível na conta bancária do cliente.",
        "Tipo": "Quantitativa",
        "Subtipo": "Contínua",
        "Relevância": "Útil"
    },
    {
        "Variável": "NumOfProducts",
        "Descrição": "Quantidade de produtos bancários adquiridos.",
        "Tipo": "Quantitativa",
        "Subtipo": "Discreta",
        "Relevância": "Útil"
    },
    {
        "Variável": "HasCrCard",
        "Descrição": "Possui cartão de crédito? (1 = Sim, 0 = Não)",
        "Tipo": "Qualitativa",
        "Subtipo": "Nominal",
        "Relevância": "Útil"
    },
    {
        "Variável": "IsActiveMember",
        "Descrição": "Cliente é ativo? (1 = Sim, 0 = Não)",
        "Tipo": "Qualitativa",
        "Subtipo": "Nominal",
        "Relevância": "Útil"
    },
    {
        "Variável": "EstimatedSalary",
        "Descrição": "Salário estimado do cliente (em moeda local).",
        "Tipo": "Quantitativa",
        "Subtipo": "Contínua",
        "Relevância": "Útil"
    },
    {
        "Variável": "Exited",
        "Descrição": "Cliente encerrou o relacionamento com o banco? (1 = Sim, 0 = Não).",
        "Tipo": "Qualitativa",
        "Subtipo": "Nominal",
        "Relevância": "Útil (variável alvo)"
    }
])

# Exibe o dicionário de dados
df_dict

"""## 📑 Descrição dos Dados

### 📖 Dicionário de Dados
| Variável            | Descrição                                              | Tipo         | Subtipo  | Relevância para Análise        |
| ------------------- | ------------------------------------------------------ | ------------ | -------- | ------------------------------ |
| **RowNumber**       | Índice da linha (número sequencial)                    | Quantitativa | Discreta | Não útil (identificador)       |
| **CustomerId**      | Identificador único do cliente                         | Qualitativa  | Nominal  | Não útil (identificador)       |
| **Surname**         | Sobrenome do cliente                                   | Qualitativa  | Nominal  | Não útil (sem valor analítico) |
| **CreditScore**     | Pontuação de crédito do cliente                        | Quantitativa | Contínua | Útil                           |
| **Geography**       | País de residência do cliente                          | Qualitativa  | Nominal  | Útil                           |
| **Gender**          | Gênero do cliente                                      | Qualitativa  | Nominal  | Útil                           |
| **Age**             | Idade do cliente                                       | Quantitativa | Contínua | Útil                           |
| **Tenure**          | Tempo de permanência como cliente (anos)               | Quantitativa | Discreta | Útil                           |
| **Balance**         | Saldo da conta bancária                                | Quantitativa | Contínua | Útil                           |
| **NumOfProducts**   | Número de produtos bancários contratados               | Quantitativa | Discreta | Útil                           |
| **HasCrCard**       | Possui cartão de crédito (1 = Sim, 0 = Não)            | Qualitativa  | Nominal  | Útil                           |
| **IsActiveMember**  | É membro ativo (1 = Sim, 0 = Não)                      | Qualitativa  | Nominal  | Útil                           |
| **EstimatedSalary** | Salário estimado do cliente                            | Quantitativa | Contínua | Útil                           |
| **Exited**          | Indicador de saída (1 = Saiu do banco, 0 = Permaneceu) | Qualitativa  | Nominal  | Útil (variável alvo)

## 📊 Análise Univariada

Exploramos cada variável individualmente para entender distribuição e outliers.
"""

# Estatísticas descritivas
df.describe()

# Histogramas para variáveis quantitativas
quant_vars = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']

for var in quant_vars:
    plt.figure(figsize=(8,4))
    sns.histplot(df[var], kde=True, bins=30)
    plt.title(f'Distribuição de {var}')
    plt.show()

# Tabelas de frequência e contagens para qualitativas
qual_vars = ['Geography', 'Gender', 'HasCrCard', 'IsActiveMember', 'Exited']

for var in qual_vars:
    print(f'\nFrequência de {var}:\n')
    print(df[var].value_counts())
    sns.countplot(x=df[var])
    plt.title(f'Contagem de {var}')
    plt.show()

"""## 🔗 Análise Bivariada

Exploramos as relações entre pares de variáveis para identificar padrões.


"""

# Matriz de correlação apenas para colunas numéricas
num_df = df.select_dtypes(include=['float64', 'int64'])
plt.figure(figsize=(10,8))
sns.heatmap(num_df.corr(), annot=True, cmap='coolwarm')
plt.title('Matriz de Correlação')
plt.show()

# Scatterplot Age vs Balance
sns.scatterplot(x='Age', y='Balance', hue='Exited', data=df)
plt.title('Idade vs. Saldo, colorido por Churn')
plt.show()

# Boxplot Balance por Geography
sns.boxplot(x='Geography', y='Balance', hue='Exited', data=df)
plt.title('Saldo por País e Churn')
plt.show()

"""## 🔬 Análise Multivariada

Analisamos interações entre três ou mais variáveis.

"""

# Pairplot
sns.pairplot(df, vars=['Age', 'Balance', 'EstimatedSalary'], hue='Exited')
plt.show()

"""## 📍 Principais Insights

- Clientes mais velhos tendem a sair mais do banco (Churn maior com idade elevada).
- A variável `Geography` mostra variações no churn — clientes da Alemanha saem mais.
- Não há correlação forte entre salário estimado e churn.
- A maioria dos clientes possui cartão de crédito, mas isso não garante retenção.
- Clientes com apenas um produto bancário têm maior taxa de saída.

## 🧠 Hipóteses

- Clientes com mais produtos têm menor propensão ao churn?
- A inatividade do cliente contribui fortemente para a saída?
- Há algum limite de idade a partir do qual o risco de churn aumenta significativamente?


"""